name: NYCsoccer
favicon: null
layout_spectrum: 0.26316
typography_spectrum: 0.880092583829537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c80014'
    - '#000000'
    - '#008a28'
    - '#8f8f8f'
  brandStrength: 1
  lightness: 0.5202344164717942
  saturation: 0.47799869254231453
  rhythmicContrast: 0.5810682629235089
purpose: []
